Update test-sql-queries.yml

diff --git a/.github/workflows/test-sql-queries.yml b/.github/workflows/test-sql-queries.yml
--- a/.github/workflows/test-sql-queries.yml
+++ b/.github/workflows/test-sql-queries.yml
@@ -20,8 +20,8 @@ jobs:
           --health-retries=5
         env:
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: testdb
+          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
+          POSTGRES_DB: ${{ env.DATABASE_NAME }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -31,20 +31,20 @@ jobs:
             sleep 1
           done
       - name: Run create-tables.sql
-        run: psql -v ON_ERROR_STOP=1 -h localhost -U postgres -d testdb -f create-tables.sql
+        run: psql -v ON_ERROR_STOP=1 -h localhost -U postgres -d ${{ env.DATABASE_NAME }} -f create-tables.sql
       - name: Ensure tables were created
         run: |
-          COUNT=$(psql -h localhost -U postgres -d testdb -t -A -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';")
+          COUNT=$(psql -h localhost -U postgres -d ${{ env.DATABASE_NAME }} -t -A -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';")
           if [ "$count" -eq 0 ]; then
             echo "No tables found. Exiting with error."
             exit 1
           fi
       - name: Run drop-tables.sql
-        run: psql -v ON_ERROR_STOP=1 -h localhost -U postgres -d testdb -f drop-tables.sql
+        run: psql -v ON_ERROR_STOP=1 -h localhost -U postgres -d ${{ env.DATABASE_NAME }} -f drop-tables.sql
       - name: Ensure all tables were dropped
         run: |
-          COUNT=$(psql -h localhost -U postgres -d testdb -t -A -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';")
+          COUNT=$(psql -h localhost -U postgres -d ${{ env.DATABASE_NAME }} -t -A -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';")
           if [ "$count" -gt 0 ]; then
-              echo "Tables found: $count. Exiting with error."
-              exit 1
+            echo "Tables found: $count. Exiting with error."
+            exit 1
           fi
