Update test-sql-queries.yml

diff --git a/.github/workflows/test-sql-queries.yml b/.github/workflows/test-sql-queries.yml
--- a/.github/workflows/test-sql-queries.yml
+++ b/.github/workflows/test-sql-queries.yml
@@ -2,6 +2,8 @@ name: Test SQL Queries
 on:
   workflow_dispatch:
   pull_request:
+env:
+  PGPASSWORD: postgres
 jobs:
   test:
     name: Test SQL Queries
@@ -29,10 +31,20 @@ jobs:
             sleep 1
           done
       - name: Run create-tables.sql
-        env:
-          PGPASSWORD: postgres
         run: psql -v ON_ERROR_STOP=1 -h localhost -U postgres -d testdb -f create-tables.sql
+      - name: Ensure tables were created
+        run: |
+          COUNT=$(psql -h localhost -U postgres -d testdb -t -A -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';")
+          if [ "$count" -eq 0 ]; then
+            echo "No tables found. Exiting with error."
+            exit 1
+          fi
       - name: Run drop-tables.sql
-        env:
-          PGPASSWORD: postgres
         run: psql -v ON_ERROR_STOP=1 -h localhost -U postgres -d testdb -f drop-tables.sql
+      - name: Ensure all tables were dropped
+        run: |
+          COUNT=$(psql -h localhost -U postgres -d testdb -t -A -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';")
+          if [ "$count" -gt 0 ]; then
+              echo "Tables found: $count. Exiting with error."
+              exit 1
+          fi
